#Check Parameters
parameters:
  - name: resourceGroup
    type: string
 
steps: # 'Steps' section is to be used inside 'job' section.
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'echo ${{ parameters.resourceGroup }}'